import Anthropic from "@anthropic-ai/sdk";
import { NextRequest } from "next/server";

const client = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

const SYSTEM_PROMPT = `You are an expert AI content detection analyst. Your job is to analyze text and score it across multiple dimensions to determine whether it was written by a human or generated by AI.

For each factor, provide:
1. A score from 0-10 where 0 = strongly AI, 10 = strongly human
2. 2-4 bullet point explanations justifying the score with specific observations from the text

Be precise, specific, and cite actual examples from the text when possible.

You must respond with ONLY valid JSON matching this exact structure:
{
  "sections": [
    {
      "name": "Structure & Flow",
      "weight": 0.12,
      "factors": [
        {
          "name": "Sentence Length Variation",
          "score": 7,
          "explanation": ["Observation 1", "Observation 2", "Observation 3"]
        }
      ]
    }
  ]
}

Score these exact sections and factors:

SECTION 1: "Structure & Flow" (weight: 0.12)
Factors: "Sentence Length Variation", "Transitional Phrase Overuse", "Predictable List Structures", "Paragraph Length Consistency"

SECTION 2: "Word Choice & Phrasing" (weight: 0.15)
Factors: "AI Filler Phrases", "Hedging Language Overuse", "Lack of Contractions", "Generic vs Specific Language"

SECTION 3: "Voice & Perspective" (weight: 0.14)
Factors: "Distinct Point of View", "Personal Anecdotes Present", "Emotional Authenticity", "Opinion Strength"

SECTION 4: "Content & Logic" (weight: 0.13)
Factors: "Depth vs Surface Treatment", "Insider/Niche Knowledge", "Surprising Observations", "Argument Completeness"

SECTION 5: "Cognitive Fingerprinting" (weight: 0.16)
Factors: "Opinion Drift / Self-Correction", "Thinking Out Loud", "Metacognitive Signals", "Cognitive Bias Presence"

SECTION 6: "Emotional Texture" (weight: 0.12)
Factors: "Genuine vs Performed Empathy", "Vulnerability Present", "Emotional Range", "Specificity of Feeling"

SECTION 7: "Pragmatics & Subtext" (weight: 0.10)
Factors: "Subtext and Implication", "Irony or Dry Humor", "Register Shifts", "Over-Explicitness"

SECTION 8: "Statistical Proxies" (weight: 0.08)
Factors: "Vocabulary Richness", "Burstiness Approximation", "Response Calibration", "Entropy Variance"

Return ONLY the JSON object. No markdown, no preamble, no explanation outside the JSON.`;

type SectionObj = {
  name: string;
  weight: number;
  score: number;
  factors: { name: string; score: number; explanation: string[] }[];
};

function scoreSection(raw: { name: string; weight: number; factors: { name: string; score: number; explanation: string[] }[] }): SectionObj {
  const sectionScore =
    raw.factors.reduce((sum, f) => sum + f.score, 0) / raw.factors.length;
  return { ...raw, score: Math.round(sectionScore * 10) / 10 };
}

function computeResult(sections: SectionObj[], wordCount: number) {
  const totalWeight = sections.reduce((sum, s) => sum + s.weight, 0);
  const aggregateScore =
    sections.reduce((sum, s) => sum + s.score * s.weight, 0) / totalWeight;
  const roundedAggregate = Math.round(aggregateScore * 10) / 10;

  let verdict: "Likely Human" | "Leans Human" | "Leans AI" | "Likely AI-Generated";
  let verdictColor: "green" | "teal" | "amber" | "red";

  if (roundedAggregate >= 7.5) {
    verdict = "Likely Human"; verdictColor = "green";
  } else if (roundedAggregate >= 5.0) {
    verdict = "Leans Human"; verdictColor = "teal";
  } else if (roundedAggregate >= 2.5) {
    verdict = "Leans AI"; verdictColor = "amber";
  } else {
    verdict = "Likely AI-Generated"; verdictColor = "red";
  }

  const confidence: "Low" | "Medium" | "High" =
    wordCount < 100 ? "Low" : wordCount < 300 ? "Medium" : "High";

  return { aggregateScore: roundedAggregate, verdict, verdictColor, wordCount, confidence, sections };
}

export async function POST(req: NextRequest) {
  const { text } = await req.json();

  if (!text || text.trim().length < 50) {
    return new Response(
      JSON.stringify({ error: "Please provide at least 50 characters of text to analyze." }),
      { status: 400, headers: { "Content-Type": "application/json" } }
    );
  }

  if (text.length > 10000) {
    return new Response(
      JSON.stringify({ error: "Text must be under 10,000 characters." }),
      { status: 400, headers: { "Content-Type": "application/json" } }
    );
  }

  const claudeStream = await client.messages.stream({
    model: "claude-haiku-4-5-20251001",
    max_tokens: 4000,
    system: SYSTEM_PROMPT,
    messages: [
      {
        role: "user",
        content: `Analyze this text for AI vs human authorship:\n\n---\n${text}\n---`,
      },
    ],
  });

  const encoder = new TextEncoder();
  const wordCount = text.trim().split(/\s+/).length;

  const stream = new ReadableStream({
    async start(controller) {
      let buffer = "";
      const send = (data: object) => {
        controller.enqueue(encoder.encode(`data: ${JSON.stringify(data)}\n\n`));
      };

      // Hoisted so final result can reuse already-parsed sections
      const parsedSections: SectionObj[] = [];
      let emittedCount = 0;

      for await (const chunk of claudeStream) {
        if (
          chunk.type === "content_block_delta" &&
          chunk.delta.type === "text_delta"
        ) {
          buffer += chunk.delta.text;

          try {
            const sectionsMatch = buffer.match(/"sections"\s*:\s*\[/);
            if (sectionsMatch) {
              const sectionsStart = buffer.indexOf(sectionsMatch[0]) + sectionsMatch[0].length;
              const partial = buffer.slice(sectionsStart);

              let depth = 0;
              let sectionStart = -1;
              const rawSections: string[] = [];

              for (let i = 0; i < partial.length; i++) {
                const ch = partial[i];
                if (ch === "{") {
                  if (depth === 0) sectionStart = i;
                  depth++;
                } else if (ch === "}") {
                  depth--;
                  if (depth === 0 && sectionStart !== -1) {
                    rawSections.push(partial.slice(sectionStart, i + 1));
                    sectionStart = -1;
                  }
                }
              }

              while (emittedCount < rawSections.length) {
                try {
                  const sectionObj = scoreSection(JSON.parse(rawSections[emittedCount]));
                  parsedSections[emittedCount] = sectionObj;
                  send({ type: "section", section: sectionObj });
                  emittedCount++;
                } catch {
                  break;
                }
              }
            }
          } catch {
            // Continue accumulating
          }
        }
      }

      // Stream done — build final result from already-parsed sections
      try {
        let sections = parsedSections.filter(Boolean);

        // Fallback: if streaming missed sections, parse raw buffer
        if (sections.length < 8) {
          const clean = buffer.replace(/```json|```/g, "").trim();
          const jsonStart = clean.indexOf("{");
          const jsonEnd = clean.lastIndexOf("}");
          const jsonStr = clean.slice(jsonStart, jsonEnd + 1);
          const parsed = JSON.parse(jsonStr);
          sections = parsed.sections.map(scoreSection);
        }

        send({ type: "complete", result: computeResult(sections, wordCount) });
      } catch (err) {
        console.error("Final parse error:", err, "Buffer tail:", buffer.slice(-300));
        send({ type: "error", message: "Failed to parse analysis results. Please try again." });
      }

      controller.close();
    },
  });

  return new Response(stream, {
    headers: {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache",
      Connection: "keep-alive",
    },
  });
}
