import type { Metadata } from "next";

const SITE_URL = "https://www.telltaleproof.com";

export const metadata: Metadata = {
  title: "Terms of Use",
  description: "TelltaleProof terms of use — the rules and conditions governing your use of our free AI content detection tool.",
  alternates: { canonical: `${SITE_URL}/terms` },
  openGraph: {
    title: "Terms of Use | TelltaleProof",
    description: "Terms and conditions for using TelltaleProof.",
    url: `${SITE_URL}/terms`,
    siteName: "TelltaleProof",
    type: "website",
  },
  robots: { index: true, follow: true },
};

export default function TermsOfUse() {
  const updated = "March 10, 2026";
  return (
    <main style={{ maxWidth: "720px", margin: "0 auto", padding: "60px 24px 80px", color: "var(--text-secondary)", fontFamily: "var(--font)", lineHeight: "1.75" }}>
      <a href="/" style={{ fontSize: "14px", color: "var(--accent)", textDecoration: "none", display: "block", marginBottom: "32px" }}>← Back to TelltaleProof</a>
      <h1 style={{ fontFamily: "var(--font)", fontSize: "40px", color: "var(--text-primary)", marginBottom: "8px", fontWeight: 700 }}>Terms of Use</h1>
      <p style={{ fontSize: "14px", color: "var(--text-muted)", marginBottom: "36px" }}>Last updated: {updated}</p>
      {[
        { title: "1. Acceptance of Terms", body: `By accessing or using TelltaleProof at telltaleproof.com ("the Service"), you agree to be bound by these Terms of Use. If you do not agree, please do not use the Service.` },
        { title: "2. Description of Service", body: `TelltaleProof is a free online tool that analyzes text to estimate the likelihood that it was written by a human or generated by artificial intelligence. Results are probabilistic and should not be treated as definitive or legally binding determinations.` },
        { title: "3. Acceptable Use", body: `You agree not to:\n\n• Submit text containing unlawful, harmful, or abusive content\n• Attempt to reverse-engineer, scrape, or automate access to the Service\n• Use the Service to deceive others in academic, legal, or employment contexts\n• Submit personally identifiable information of others without their consent\n• Use the Service in any way that could damage or impair it` },
        { title: "4. Disclaimer of Warranties", body: `THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. AI detection is an imperfect science. Scores should be used as one signal among many, not as a definitive determination of authorship. We do not warrant accuracy, reliability, or fitness for any particular purpose.` },
        { title: "5. Limitation of Liability", body: `TO THE MAXIMUM EXTENT PERMITTED BY LAW, WEB THRIVE, LLC SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING FROM YOUR USE OF THE SERVICE, INCLUDING DECISIONS MADE BASED ON ANALYSIS RESULTS.` },
        { title: "6. Intellectual Property", body: `The TelltaleProof name, logo, interface, and methodology are proprietary to Web Thrive, LLC. Text you submit remains your property. By submitting text, you grant us a limited license to process it solely to provide the Service.` },
        { title: "7. Advertising", body: `TelltaleProof displays advertisements via Google AdSense and potentially other networks. We are not responsible for third-party ad content.` },
        { title: "8. Modifications", body: `We reserve the right to modify or discontinue the Service at any time. We may update these Terms from time to time. Continued use constitutes acceptance of updated Terms.` },
        { title: "9. Governing Law", body: `These Terms are governed by the laws of the State of California, United States.` },
        { title: "10. Contact", body: `Questions? Contact us at: hello@telltaleproof.com` },
      ].map((s) => (
        <div key={s.title} style={{ marginBottom: "32px" }}>
          <h2 style={{ fontSize: "20px", color: "var(--text-primary)", marginBottom: "10px", fontWeight: 600 }}>{s.title}</h2>
          <p style={{ fontSize: "15px", whiteSpace: "pre-line" }}>{s.body}</p>
        </div>
      ))}
    </main>
  );
}
