import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import type { Metadata } from "next";

const SITE_URL = "https://www.contenttrace.ai";

export const metadata: Metadata = {
  title: "Disclaimer | Content Trace",
  description: "Content Trace disclaimer — important information about the limitations of AI detection and how results should be interpreted.",
  alternates: { canonical: `${SITE_URL}/disclaimer` },
  openGraph: {
    title: "Disclaimer | Content Trace",
    description: "Important information about the limitations of AI detection results from Content Trace.",
    url: `${SITE_URL}/disclaimer`,
    siteName: "Content Trace",
    type: "website",
  },
  robots: { index: true, follow: true },
};

const sections = [
  {
    title: "1. Results Are Probabilistic, Not Definitive",
    body: `Content Trace analyzes text across 32 signals to produce a Human Score between 0 and 100. This score represents a probabilistic estimate of the likelihood that the analyzed text was written by a human, not a definitive determination of authorship.\n\nNo AI detection tool — including Content Trace — can determine with certainty whether a piece of text was written by a human or generated by an AI system. The field of AI detection is still evolving, and all existing methods have meaningful error rates.`,
  },
  {
    title: "2. Do Not Use Results as Evidence",
    body: `Results from Content Trace must not be used as evidence in academic, legal, employment, disciplinary, or any other formal proceedings. A low Human Score does not prove that text was AI-generated, and a high Human Score does not prove that text was written by a human.\n\nUsing probabilistic detection scores as a basis for academic penalties, employment decisions, or legal action could cause significant harm to individuals and is expressly discouraged.`,
  },
  {
    title: "3. Factors That Affect Score Accuracy",
    body: `AI detection scores can be significantly affected by factors unrelated to actual AI usage, including:\n\n• Writing style: Formal, technical, or highly edited writing can score lower on Human scales even when written entirely by a human.\n• Text length: Very short texts (under 100 words) produce less reliable scores due to limited signal data.\n• Translation: Text that has been translated, whether by a human or machine, may produce inaccurate results.\n• Editing and paraphrasing: Heavily edited or paraphrased text — whether AI-generated or human-written — can confuse detection models.\n• Subject matter: Highly technical, formulaic, or templated content (such as legal boilerplate or scientific abstracts) may score lower regardless of authorship.\n• Non-native English: Writers working in English as a second language may exhibit patterns that detection models associate with AI.`,
  },
  {
    title: "4. No Warranty",
    body: `Content Trace is provided free of charge and on an \"as is\" basis, without warranty of any kind, express or implied. Web Thrive, LLC makes no representations or warranties regarding the accuracy, completeness, or fitness for purpose of the analysis results.\n\nWe do not warrant that the service will be uninterrupted, error-free, or that any particular result will be correct.`,
  },
  {
    title: "5. Limitation of Liability",
    body: `To the fullest extent permitted by applicable law, Web Thrive, LLC and its operators, employees, and affiliates shall not be liable for any direct, indirect, incidental, special, or consequential damages arising from the use of Content Trace or reliance on its results.\n\nThis includes, but is not limited to, damages arising from academic or employment decisions, reputational harm, or any other outcome resulting from the use or misuse of Content Trace analysis results.`,
  },
  {
    title: "6. Intended Use",
    body: `Content Trace is intended as an educational and informational tool to help writers, educators, and content professionals understand patterns in writing. It is designed to support — not replace — human judgment.\n\nAppropriate uses include: reviewing your own writing for AI-like patterns, understanding what signals differentiate human and AI writing, and screening content as one of several inputs in a broader editorial review process.\n\nInappropriate uses include: making unilateral decisions about academic dishonesty, using scores to take action against individuals, or treating results as forensic evidence of any kind.`,
  },
  {
    title: "7. Changes to This Disclaimer",
    body: `We may update this disclaimer from time to time. Continued use of Content Trace after any changes constitutes acceptance of the revised disclaimer. The last updated date at the top of this page reflects when the most recent revision was made.`,
  },
];

export default function DisclaimerPage() {
  const updated = "April 2, 2026";
  return (
    <>
      <Nav current="/disclaimer" />
      <main style={{ maxWidth: "720px", margin: "0 auto", padding: "60px 24px 80px", color: "var(--text-secondary)", fontFamily: "var(--font)", lineHeight: "1.75" }}>

        <h1 style={{ fontFamily: "var(--font)", fontSize: "40px", color: "var(--text-primary)", marginBottom: "8px", fontWeight: 700, letterSpacing: "-0.02em" }}>Disclaimer</h1>
        <p style={{ fontSize: "14px", color: "var(--text-muted)", marginBottom: "12px" }}>Last updated: {updated}</p>
        <p style={{ fontSize: "16px", color: "var(--text-secondary)", marginBottom: "40px", lineHeight: "1.7", padding: "16px 20px", background: "var(--bg-elevated)", borderRadius: "10px", border: "1px solid var(--border)" }}>
          Content Trace provides probabilistic analysis only. Results are not a definitive determination of authorship and should not be used as evidence in any formal proceedings. Please read this disclaimer carefully before using or relying on any results from Content Trace.
        </p>

        {sections.map((sec) => (
          <div key={sec.title} style={{ marginBottom: "36px" }}>
            <h2 style={{ fontSize: "20px", fontWeight: 700, color: "var(--text-primary)", marginBottom: "12px" }}>{sec.title}</h2>
            {sec.body.split("\n\n").map((para, i) => (
              <p key={i} style={{ fontSize: "16px", color: "var(--text-secondary)", marginBottom: "14px", lineHeight: "1.75", whiteSpace: "pre-line" }}>{para}</p>
            ))}
          </div>
        ))}

        <div style={{ marginTop: "48px", padding: "20px 24px", background: "var(--bg-elevated)", border: "1px solid var(--border)", borderRadius: "10px", fontSize: "14px", color: "var(--text-muted)", lineHeight: "1.7" }}>
          Questions about this disclaimer? Contact us at{" "}
          <a href="mailto:hello@contenttrace.ai" style={{ color: "var(--accent)", textDecoration: "none" }}>hello@contenttrace.ai</a>
          {" "}or visit our <a href="/contact" style={{ color: "var(--accent)", textDecoration: "none" }}>Contact page</a>.
        </div>
      </main>
      <Footer />
    </>
  );
}
